{
 "title": "Bus data",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tags_bus",
    "label": "Bus",
    "query": "show tag values from \"bus_data\" with key=\"tags_bus\""
   }
  ]
 },
 "panels": [
  {
   "title": "Bus Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "alias": "Bus $tag_tags_bus",
     "groupBy": [
      { "params": [ "fields_generation_q::field" ], "type": "tag" }
     ],
     "measurement": "bus_data",
     "query": "SELECT \"fields_voltage_magnitude\" FROM \"autogen\".\"bus_data\" WHERE (\"tags_bus\"::tag =~ /^$tags_bus$/) AND $timeFilter GROUP BY \"tags_bus\"::tag",
     "select": [
      [
       { "params": [ "fields_voltage_magnitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tags_bus::tag", "operator": "=~", "value": "/^$tags_bus$/" }
     ]
    }
   ]
  },
  {
   "title": "Bus Voltage Angle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "alias": "Bus $tag_tags_bus",
     "groupBy": [
      { "params": [ "fields_generation_q::field" ], "type": "tag" }
     ],
     "measurement": "bus_data",
     "query": "SELECT \"fields_voltage_angle\" FROM \"autogen\".\"bus_data\" WHERE (\"tags_bus\"::tag =~ /^$tags_bus$/) AND $timeFilter GROUP BY \"tags_bus\"::tag",
     "select": [
      [
       { "params": [ "fields_voltage_magnitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tags_bus::tag", "operator": "=~", "value": "/^$tags_bus$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Power Injection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "alias": "Bus $tag_tags_bus",
     "groupBy": [
      { "params": [ "fields_generation_q::field" ], "type": "tag" }
     ],
     "measurement": "bus_data",
     "query": "SELECT -\"fields_load_p\" FROM \"autogen\".\"bus_data\" WHERE (\"tags_bus\"::tag =~ /^$tags_bus$/) AND $timeFilter GROUP BY \"tags_bus\"::tag",
     "select": [
      [
       { "params": [ "fields_voltage_magnitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tags_bus::tag", "operator": "=~", "value": "/^$tags_bus$/" }
     ]
    }
   ]
  },
  {
   "title": "Reactive Power Injection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MVar" } },
   "targets": [
    {
     "alias": "Bus $tag_tags_bus",
     "groupBy": [
      { "params": [ "fields_generation_q::field" ], "type": "tag" }
     ],
     "measurement": "bus_data",
     "query": "SELECT -\"fields_load_q\" FROM \"autogen\".\"bus_data\" WHERE (\"tags_bus\"::tag =~ /^$tags_bus$/) AND $timeFilter GROUP BY \"tags_bus\"::tag",
     "select": [
      [
       { "params": [ "fields_voltage_magnitude" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "tags_bus::tag", "operator": "=~", "value": "/^$tags_bus$/" }
     ]
    }
   ]
  }
 ]
}