{
 "title": "Meta",
 "time": { "from": "2023-07-23T22:00:00.000Z", "to": "2023-07-28T21:59:59.000Z" },
 "panels": [
  {
   "title": "Std. Dev.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pu" } },
   "targets": [
    {
     "query": "SELECT \"fields_value\" FROM \"autogen\".\"se_meta\" WHERE (\"tags_metric\" = 'worst_std_dev') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Conv. Objective",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "se_meta",
     "query": "SELECT \"fields_value\" FROM \"autogen\".\"se_meta\" WHERE (\"tags_metric\"::tag = 'convergence_objective') AND $timeFilter ",
     "select": [
      [
       { "params": [ "fields_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tags_metric::tag", "operator": "=", "value": "convergence_objective" }
     ]
    }
   ]
  },
  {
   "title": "Mismatch P",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "se_meta",
     "query": "SELECT \"fields_value\",\"fields_node\" FROM \"se_meta\" WHERE (\"tags_metric\"::tag = 'missmatch_p') AND $timeFilter ",
     "select": [
      [
       { "params": [ "fields_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tags_metric::tag", "operator": "=", "value": "convergence_objective" }
     ]
    }
   ]
  },
  {
   "title": "Mismatch Q",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "se_meta",
     "query": "SELECT \"fields_value\", \"fields_node\" FROM \"se_meta\" WHERE (\"tags_metric\"::tag = 'missmatch_q') AND $timeFilter ",
     "select": [
      [
       { "params": [ "fields_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tags_metric::tag", "operator": "=", "value": "convergence_objective" }
     ]
    }
   ]
  },
  {
   "title": "Conv. Voltage Angle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "se_meta",
     "query": "SELECT \"fields_value\" FROM \"autogen\".\"se_meta\" WHERE (\"tags_metric\"::tag = 'convergence_voltage_ang') AND $timeFilter ",
     "select": [
      [
       { "params": [ "fields_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tags_metric::tag", "operator": "=", "value": "convergence_objective" }
     ]
    }
   ]
  },
  {
   "title": "Conv. Voltage Magnitude",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "se_meta",
     "query": "SELECT * FROM \"autogen\".\"se_meta\" WHERE (\"tags_metric\"::tag = 'convergence_voltage_mag') AND $timeFilter ",
     "select": [
      [
       { "params": [ "fields_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tags_metric::tag", "operator": "=", "value": "convergence_objective" }
     ]
    }
   ]
  },
  {
   "title": "Weighted MSE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "se_meta",
     "query": "SELECT * FROM \"autogen\".\"se_meta\" WHERE (\"tags_metric\"::tag = 'weighted_mse') AND $timeFilter ",
     "select": [
      [
       { "params": [ "fields_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tags_metric::tag", "operator": "=", "value": "convergence_objective" }
     ]
    }
   ]
  }
 ]
}