apiVersion: 1.0

datasources:
  - name: State-Estimation
    type: influxdb
    typeName: "InfluxDB"
    typeLogoUrl: "public/app/plugins/datasource/influxdb/img/influxdb_logo.svg"
    access: "proxy"
    url: "http://influxdb:8086"
    user: "grafana"
    basicAuth: false
    isDefault: true
    jsonData:
      dbName: "platone"
      httpMode: "POST"
    readOnly: true